/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

/**
 *
 * @author HP
 */
public class HeritageBistroLal extends javax.swing.JFrame {

    /**
     * Creates new form HeritageBistroLal
     */
     int i=0,j=0,p=230,p2=180;
      String st="Set Menu 1";
      String st2="Set Menu 2";
    public HeritageBistroLal() {
        initComponents();
    }
     public HeritageBistroLal(int i,int j)
    {
        initComponents();
        this.i=i;
        this.j=j;
        FstQShow.setText(String.valueOf(this.i));
        SecndQShow.setText(String.valueOf(this.j));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        FstFoodName = new javax.swing.JLabel();
        FstPrice = new javax.swing.JLabel();
        FstFoodPic = new javax.swing.JLabel();
        food1plus = new javax.swing.JButton();
        FstQShow = new javax.swing.JTextField();
        food1minus = new javax.swing.JButton();
        secndFoodName = new javax.swing.JLabel();
        SecndPrice = new javax.swing.JLabel();
        Secndpic = new javax.swing.JLabel();
        food2plus = new javax.swing.JButton();
        SecndQShow = new javax.swing.JTextField();
        food2minus = new javax.swing.JButton();
        Order = new javax.swing.JButton();
        foodItem1 = new javax.swing.JLabel();
        foodItem2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/rsz_heritagelogo.jpg"))); // NOI18N
        Title.setText("jLabel1");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 340, 110));

        Back.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 130, 60));

        FstFoodName.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        FstFoodName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/rsz_set_menu1hr.jpg"))); // NOI18N
        FstFoodName.setText("jLabel2");
        getContentPane().add(FstFoodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 230, 150));

        FstPrice.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        FstPrice.setText("Set menu 1");
        getContentPane().add(FstPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 160, -1));

        FstFoodPic.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        FstFoodPic.setText("Price: 230");
        getContentPane().add(FstFoodPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 140, -1));

        food1plus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        food1plus.setText("+");
        food1plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food1plusActionPerformed(evt);
            }
        });
        getContentPane().add(food1plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 50, 40));

        FstQShow.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        FstQShow.setText("    0");
        FstQShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FstQShowActionPerformed(evt);
            }
        });
        getContentPane().add(FstQShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 80, 40));

        food1minus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        food1minus.setText("-");
        food1minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food1minusActionPerformed(evt);
            }
        });
        getContentPane().add(food1minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 50, 40));

        secndFoodName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/rsz_set_menu2hr.jpg"))); // NOI18N
        secndFoodName.setText("jLabel5");
        getContentPane().add(secndFoodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 230, 150));

        SecndPrice.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        SecndPrice.setText("Set menu 2");
        getContentPane().add(SecndPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 170, -1));

        Secndpic.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        Secndpic.setText("Price : 180");
        getContentPane().add(Secndpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 140, -1));

        food2plus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        food2plus.setText("+");
        food2plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food2plusActionPerformed(evt);
            }
        });
        getContentPane().add(food2plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 50, 40));

        SecndQShow.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        SecndQShow.setText("    0");
        SecndQShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecndQShowActionPerformed(evt);
            }
        });
        getContentPane().add(SecndQShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 80, 40));

        food2minus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        food2minus.setText("-");
        food2minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food2minusActionPerformed(evt);
            }
        });
        getContentPane().add(food2minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 50, 40));

        Order.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        Order.setText("Order");
        Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderActionPerformed(evt);
            }
        });
        getContentPane().add(Order, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, 120, 60));

        foodItem1.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        foodItem1.setText("(Fried rice,Grilled Chicken,Vegetable,Chicken Curry)");
        getContentPane().add(foodItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        foodItem2.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        foodItem2.setText("(Fried rice,Grilled Chicken,Vegetable)");
        getContentPane().add(foodItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/heritageBack.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -20, -1, -1));

        setSize(new java.awt.Dimension(1215, 695));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void food2minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food2minusActionPerformed
        // TODO add your handling code here:
         if(j>0)
            j--;
        SecndQShow.setText(String.valueOf(j));
    }//GEN-LAST:event_food2minusActionPerformed

    private void SecndQShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecndQShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecndQShowActionPerformed

    private void OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderActionPerformed
        // TODO add your handling code here:
        new Order(i,j,st,st2,p,p2).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OrderActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        new Lalbag().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void food1plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food1plusActionPerformed
        // TODO add your handling code here:
         i++;
        FstQShow.setText(String.valueOf(i));       
    }//GEN-LAST:event_food1plusActionPerformed

    private void FstQShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FstQShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FstQShowActionPerformed

    private void food1minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food1minusActionPerformed
        // TODO add your handling code here:
          if(i>0)
            i--;
       FstQShow.setText(String.valueOf(i));     
    }//GEN-LAST:event_food1minusActionPerformed

    private void food2plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food2plusActionPerformed
  j++;
       SecndQShow.setText(String.valueOf(j));        // TODO add your handling code here:
    }//GEN-LAST:event_food2plusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HeritageBistroLal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HeritageBistroLal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HeritageBistroLal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HeritageBistroLal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HeritageBistroLal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel FstFoodName;
    private javax.swing.JLabel FstFoodPic;
    private javax.swing.JLabel FstPrice;
    private javax.swing.JTextField FstQShow;
    private javax.swing.JButton Order;
    private javax.swing.JLabel SecndPrice;
    private javax.swing.JTextField SecndQShow;
    private javax.swing.JLabel Secndpic;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel background;
    private javax.swing.JButton food1minus;
    private javax.swing.JButton food1plus;
    private javax.swing.JButton food2minus;
    private javax.swing.JButton food2plus;
    private javax.swing.JLabel foodItem1;
    private javax.swing.JLabel foodItem2;
    private javax.swing.JLabel secndFoodName;
    // End of variables declaration//GEN-END:variables
}
