/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

/**
 *
 * @author HP
 */
public class KrispyKremeBanani extends javax.swing.JFrame {

    /**
     * Creates new form KrispyKremeBanani
     */ 
    int i=0,j=0,p=275,p2=120;
      String st="Mixed Choco Nuts Donuts";
      String st2="Chocolate Cold Coffee";
    
    public KrispyKremeBanani() {
        initComponents();
    }
     public KrispyKremeBanani(int i,int j)
    {
        initComponents();
        this.i=i;
        this.j=j;
        FstQShow.setText(String.valueOf(this.i));
        SecndQShow.setText(String.valueOf(this.j));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        FstFoodName = new javax.swing.JLabel();
        FstPrice = new javax.swing.JLabel();
        FstFoodPic = new javax.swing.JLabel();
        food1plus = new javax.swing.JButton();
        food1Minus = new javax.swing.JButton();
        SecndFoodPic = new javax.swing.JLabel();
        SecndName = new javax.swing.JLabel();
        SecndPrice = new javax.swing.JLabel();
        food2plus = new javax.swing.JButton();
        food2minus = new javax.swing.JButton();
        FstQShow = new javax.swing.JTextField();
        SecndQShow = new javax.swing.JTextField();
        Order = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Ravie", 3, 24)); // NOI18N
        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/rsz_krispy.png"))); // NOI18N
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 680, 160));

        Back.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 130, 60));

        FstFoodName.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        FstFoodName.setForeground(new java.awt.Color(255, 255, 51));
        FstFoodName.setText("Mixed Choco Nuts Donuts");
        getContentPane().add(FstFoodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 350, -1));

        FstPrice.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        FstPrice.setForeground(new java.awt.Color(255, 255, 51));
        FstPrice.setText("Price: 275 Tk");
        getContentPane().add(FstPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, -1));

        FstFoodPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/rsz_donuts.jpg"))); // NOI18N
        FstFoodPic.setText("food pic");
        getContentPane().add(FstFoodPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 230, 150));

        food1plus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        food1plus.setText("+");
        food1plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food1plusActionPerformed(evt);
            }
        });
        getContentPane().add(food1plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, 50, 40));

        food1Minus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        food1Minus.setText("-");
        food1Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food1MinusActionPerformed(evt);
            }
        });
        getContentPane().add(food1Minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 50, 40));

        SecndFoodPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/rsz_cold_coffe.jpg"))); // NOI18N
        SecndFoodPic.setText("Secnd food pic");
        getContentPane().add(SecndFoodPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 230, 140));

        SecndName.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        SecndName.setForeground(new java.awt.Color(255, 255, 51));
        SecndName.setText("Chocolate Cold Coffee");
        getContentPane().add(SecndName, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 290, -1));

        SecndPrice.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        SecndPrice.setForeground(new java.awt.Color(255, 255, 51));
        SecndPrice.setText("Price: 120Tk");
        getContentPane().add(SecndPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, -1, 30));

        food2plus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        food2plus.setText("+");
        food2plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food2plusActionPerformed(evt);
            }
        });
        getContentPane().add(food2plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, 50, 40));

        food2minus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        food2minus.setText("-");
        food2minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food2minusActionPerformed(evt);
            }
        });
        getContentPane().add(food2minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 50, 40));

        FstQShow.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        FstQShow.setText("   0");
        FstQShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FstQShowActionPerformed(evt);
            }
        });
        getContentPane().add(FstQShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 80, 40));

        SecndQShow.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        SecndQShow.setText("    0");
        SecndQShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecndQShowActionPerformed(evt);
            }
        });
        getContentPane().add(SecndQShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 80, 40));

        Order.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        Order.setText("Order");
        Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderActionPerformed(evt);
            }
        });
        getContentPane().add(Order, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, 120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/krispyback.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -190, -1, -1));

        setSize(new java.awt.Dimension(1215, 695));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        new Banani().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void food1plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food1plusActionPerformed
         i++;
        FstQShow.setText(String.valueOf(i));        // TODO add your handling code here:
    }//GEN-LAST:event_food1plusActionPerformed

    private void SecndQShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecndQShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecndQShowActionPerformed

    private void food1MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food1MinusActionPerformed
    
        if(i>0)
            i--;
       FstQShow.setText(String.valueOf(i));        // TODO add your handling code here:
    }//GEN-LAST:event_food1MinusActionPerformed

    private void food2plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food2plusActionPerformed
        // TODO add your handling code here:
         j++;
       SecndQShow.setText(String.valueOf(j));
    }//GEN-LAST:event_food2plusActionPerformed

    private void food2minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food2minusActionPerformed
        // TODO add your handling code here:
        if(j>0)
            j--;
        SecndQShow.setText(String.valueOf(j));
    }//GEN-LAST:event_food2minusActionPerformed

    private void OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderActionPerformed
        // TODO add your handling code here:
       new Order(i,j,st,st2,p,p2).setVisible(true);
       this.dispose();
    }//GEN-LAST:event_OrderActionPerformed

    private void FstQShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FstQShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FstQShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KrispyKremeBanani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KrispyKremeBanani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KrispyKremeBanani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KrispyKremeBanani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KrispyKremeBanani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel FstFoodName;
    private javax.swing.JLabel FstFoodPic;
    private javax.swing.JLabel FstPrice;
    private javax.swing.JTextField FstQShow;
    private javax.swing.JButton Order;
    private javax.swing.JLabel SecndFoodPic;
    private javax.swing.JLabel SecndName;
    private javax.swing.JLabel SecndPrice;
    private javax.swing.JTextField SecndQShow;
    private javax.swing.JLabel Title;
    private javax.swing.JButton food1Minus;
    private javax.swing.JButton food1plus;
    private javax.swing.JButton food2minus;
    private javax.swing.JButton food2plus;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
