/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

/**
 *
 * @author Sakib
 */
public class Sultan extends javax.swing.JFrame {

    /**
     * Creates new form Sultan
     */
          int i=0,j=0,p=350,p2=1300;
          String st="Kacchi Platter 1person";
          String st2="Kacchi Platter 4 person";
    public Sultan() {
        initComponents();
    }
    public Sultan(int i,int j)
    {
        initComponents();
        this.i=i;
        this.j=j;
        Platter2Order.setText(String.valueOf(this.j));
        Platter1Order.setText(String.valueOf(this.i));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Platter1 = new javax.swing.JLabel();
        NameBur = new javax.swing.JLabel();
        BeefChessePrice = new javax.swing.JLabel();
        Platter1Minus = new javax.swing.JButton();
        Platter1Plus = new javax.swing.JButton();
        Platter2Minus = new javax.swing.JButton();
        Platter2Plus = new javax.swing.JButton();
        Platter1Order = new javax.swing.JTextField();
        Platter2 = new javax.swing.JLabel();
        BeefName = new javax.swing.JLabel();
        BeefPrice = new javax.swing.JLabel();
        Platter2Order = new javax.swing.JTextField();
        Order = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Platter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/Platter1.jpg"))); // NOI18N
        getContentPane().add(Platter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, 140));

        NameBur.setBackground(new java.awt.Color(255, 255, 255));
        NameBur.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        NameBur.setText("Kacchi Platter 1person");
        getContentPane().add(NameBur, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 310, 50));

        BeefChessePrice.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        BeefChessePrice.setText("Price: 350 TK");
        getContentPane().add(BeefChessePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 190, -1));

        Platter1Minus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        Platter1Minus.setText("-");
        Platter1Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Platter1MinusActionPerformed(evt);
            }
        });
        getContentPane().add(Platter1Minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 50, 40));

        Platter1Plus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        Platter1Plus.setText("+");
        Platter1Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Platter1PlusActionPerformed(evt);
            }
        });
        getContentPane().add(Platter1Plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 50, 40));

        Platter2Minus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        Platter2Minus.setText("-");
        Platter2Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Platter2MinusActionPerformed(evt);
            }
        });
        getContentPane().add(Platter2Minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 50, 40));

        Platter2Plus.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        Platter2Plus.setText("+");
        Platter2Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Platter2PlusActionPerformed(evt);
            }
        });
        getContentPane().add(Platter2Plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 50, 40));

        Platter1Order.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        Platter1Order.setText("   0");
        Platter1Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Platter1OrderActionPerformed(evt);
            }
        });
        getContentPane().add(Platter1Order, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 80, 40));

        Platter2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/Platter2.jpg"))); // NOI18N
        getContentPane().add(Platter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 250, 140));

        BeefName.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        BeefName.setText("Kacchi Platter 4 person");
        getContentPane().add(BeefName, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 320, 40));

        BeefPrice.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        BeefPrice.setText("Price: 1300 TK");
        getContentPane().add(BeefPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 190, -1));

        Platter2Order.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        Platter2Order.setText("   0");
        Platter2Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Platter2OrderActionPerformed(evt);
            }
        });
        getContentPane().add(Platter2Order, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 80, 40));

        Order.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        Order.setText("Order");
        Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderActionPerformed(evt);
            }
        });
        getContentPane().add(Order, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 120, 60));

        back.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 130, 60));

        jLabel5.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        jLabel5.setText("(kacchi,Borhani)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 220, -1));

        jLabel4.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        jLabel4.setText("(kacchi,Borhani)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 220, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/SultanLogo.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 35, 330, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/back label.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -40, -1, -1));

        setSize(new java.awt.Dimension(1215, 695));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Platter1MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Platter1MinusActionPerformed

        i--;
        Platter1Order.setText(String.valueOf(i));
    }//GEN-LAST:event_Platter1MinusActionPerformed

    private void Platter1PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Platter1PlusActionPerformed
        // TODO add your handling code here:

        i++;
        Platter1Order.setText(String.valueOf(i));

    }//GEN-LAST:event_Platter1PlusActionPerformed

    private void Platter2MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Platter2MinusActionPerformed
        // TODO add your handling code here:
        if(j>0)
        {
            j--;
        }
        Platter2Order.setText(String.valueOf(j));
    }//GEN-LAST:event_Platter2MinusActionPerformed

    private void Platter2PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Platter2PlusActionPerformed
        // TODO add your handling code here:
        j++;
        Platter2Order.setText(String.valueOf(j));
    }//GEN-LAST:event_Platter2PlusActionPerformed

    private void Platter1OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Platter1OrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Platter1OrderActionPerformed

    private void Platter2OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Platter2OrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Platter2OrderActionPerformed

    private void OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderActionPerformed
        // TODO add your handling code here:
        new Order(i,j,st,st2,p,p2).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OrderActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new Dhanmondi().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sultan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BeefChessePrice;
    private javax.swing.JLabel BeefName;
    private javax.swing.JLabel BeefPrice;
    private javax.swing.JLabel NameBur;
    private javax.swing.JButton Order;
    private javax.swing.JLabel Platter1;
    private javax.swing.JButton Platter1Minus;
    private javax.swing.JTextField Platter1Order;
    private javax.swing.JButton Platter1Plus;
    private javax.swing.JLabel Platter2;
    private javax.swing.JButton Platter2Minus;
    private javax.swing.JTextField Platter2Order;
    private javax.swing.JButton Platter2Plus;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
